import { DirectoryItem, Category } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Нейросети' },
  { id: 'cat-2', name: 'Дизайн' },
  { id: 'cat-3', name: 'Программирование' },
  { id: 'cat-4', name: 'Маркетинг' },
  { id: 'cat-5', name: 'Образование' },
  { id: 'cat-6', name: 'Продуктивность' }
];

export const INITIAL_ITEMS: Partial<DirectoryItem>[] = [
  {
    title: 'ChatGPT',
    shortDescription: 'Самый популярный чат-бот на базе ИИ от OpenAI.',
    fullDescription: 'ChatGPT — это чат-бот с искусственным интеллектом, разработанный компанией OpenAI и способный работать в диалоговом режиме, поддерживающий запросы на естественных языках.',
    category: 'Нейросети',
    type: 'Website',
    imageUrl: 'https://picsum.photos/seed/chatgpt/800/450',
    purpose: 'Общение и генерация контента',
    pricing: 'Freemium',
    subscriptionPrice: '$20/мес за Plus',
    platforms: ['Web', 'Android', 'iOS'],
    pros: ['Высокая скорость', 'Поддержка русского языка', 'Огромная база знаний'],
    cons: ['Иногда галлюцинирует', 'Ограничение знаний до 2023 года'],
    alternatives: ['Claude', 'Gemini', 'Perplexity'],
    link: 'https://chat.openai.com',
    averageRating: 4.8,
    totalRatings: 1250,
    viewsCount: 5000,
    isNew: false,
    isTopRated: true,
    targetAudience: { level: 'Beginner', role: 'All', pc: 'All' }
  },
  {
    title: 'Figma',
    shortDescription: 'Онлайн-сервис для разработки интерфейсов и прототипирования.',
    fullDescription: 'Figma — это кросс-платформенный онлайн-сервис для дизайнеров интерфейсов и веб-разработчиков.',
    category: 'Дизайн',
    type: 'App',
    imageUrl: 'https://picsum.photos/seed/figma/800/450',
    purpose: 'Дизайн интерфейсов',
    pricing: 'Freemium',
    subscriptionPrice: 'от $12/мес',
    platforms: ['Web', 'Android', 'iOS'],
    pros: ['Совместная работа', 'Много плагинов', 'Бесплатно для личного пользования'],
    cons: ['Нужен интернет', 'Сложно для новичков'],
    alternatives: ['Adobe XD', 'Sketch', 'Penpot'],
    link: 'https://figma.com',
    averageRating: 4.9,
    totalRatings: 850,
    viewsCount: 3200,
    isNew: false,
    isTopRated: true,
    targetAudience: { level: 'Pro', role: 'Developer', pc: 'All' }
  },
  {
    title: 'Visual Studio Code',
    shortDescription: 'Самый популярный редактор кода от Microsoft.',
    fullDescription: 'Visual Studio Code — редактор исходного кода, разработанный Microsoft для Windows, Linux и macOS.',
    category: 'Программирование',
    type: 'App',
    imageUrl: 'https://picsum.photos/seed/vscode/800/450',
    purpose: 'Написание кода',
    pricing: 'Free',
    platforms: ['Web'],
    pros: ['Огромное количество расширений', 'Быстрая работа', 'Встроенный терминал'],
    cons: ['Может потреблять много памяти с плагинами'],
    alternatives: ['WebStorm', 'Sublime Text', 'Atom'],
    link: 'https://code.visualstudio.com',
    averageRating: 4.9,
    totalRatings: 2100,
    viewsCount: 8000,
    isNew: false,
    isTopRated: true,
    targetAudience: { level: 'Beginner', role: 'Developer', pc: 'All' }
  },
  {
    title: 'Notion',
    shortDescription: 'Универсальное рабочее пространство для заметок и задач.',
    fullDescription: 'Notion — приложение, предоставляющее такие компоненты, как базы данных, канбан-доски, вики, календари и напоминания.',
    category: 'Продуктивность',
    type: 'App',
    imageUrl: 'https://picsum.photos/seed/notion/800/450',
    purpose: 'Организация работы',
    pricing: 'Freemium',
    subscriptionPrice: 'от $8/мес',
    platforms: ['Web', 'Android', 'iOS'],
    pros: ['Гибкость', 'Красивый дизайн', 'Много шаблонов'],
    cons: ['Сложная кривая обучения', 'Медленная загрузка'],
    alternatives: ['Obsidian', 'Evernote', 'Trello'],
    link: 'https://notion.so',
    averageRating: 4.7,
    totalRatings: 920,
    viewsCount: 4500,
    isNew: false,
    isTopRated: true,
    targetAudience: { level: 'Beginner', role: 'All', pc: 'All' }
  }
];
